<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exceptions\**" />
    <Compile Remove="Interfaces\**" />
    <Content Remove="Exceptions\**" />
    <Content Remove="Interfaces\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <None Remove="Exceptions\**" />
    <None Remove="Interfaces\**" />
  </ItemGroup>

</Project>
