# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - car-rental

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build Maintenance.WebAPI/Maintenance.WebAPI.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Maintenance.WebAPI/Maintenance.WebAPI.csproj -c Release -o ${{env.DOTNET_ROOT}}/carrental-maintenance

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/carrental-maintenance

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # - name: Login to Azure
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_77FECDA6FA3E481AA9ED451AD33E0226 }}
      #     tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_456BDCCD14A444E1A699589FBBFC5A36 }}
      #     subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9AD9CE4FC9CE46C58629126802852516 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'maintenance-webapi'
          slot-name: 'Production'
          publish-profile: 'AZURE_WEBAPP_PUBLISH_PROFILE'
          package: .

          



